# Generated by Django 5.2.9 on 2025-12-30 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(db_column='pk_id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rajaongkir_id', models.IntegerField(unique=True)),
                ('province_id', models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='feeongkir.province')),
            ],
        ),
    ]
