# Generated by Django 5.2.9 on 2025-12-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeongkir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='id',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False, unique=True),
        ),
    ]
