# Generated by Django 5.2.9 on 2025-12-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeongkir', '0002_alter_province_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'managed': False},
        ),
    ]
